# Generated by Django 2.0.3 on 2018-03-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='address1',
            new_name='address',
        ),
    ]
