# Generated by Django 2.0.3 on 2018-03-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_auto_20180321_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('catagory', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=256)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
