# Generated by Django 2.0.3 on 2018-03-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0004_auto_20180321_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
